inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/**/*
    - vendor/bundle/**/*

Bundler/OrderedGems:
  Enabled: true

Rails:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '()'
    '%i': '()'
    '%q': '()'
    '%Q': '()'
    '%r': '{}'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/WordArray:
  EnforcedStyle: percent
