inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - db/**/*
    - vendor/bundle/**/*
  NewCops: enable

Bundler/OrderedGems:
  Enabled: true

Rails:
  Enabled: true
