inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - db/**/*
    - vendor/bundle/**/*
  NewCops: enable

Bundler/OrderedGems:
  Enabled: true

Rails:
  Enabled: true
