# fly.toml app configuration file generated for carrotgram on 2023-07-27T15:34:02+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "carrotgram"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    BUNDLER_VERSION = "2.3.17"
    NODE_VERSION = "18"
    RUBY_VERSION = "3.2.2"

[deploy]
  release_command = "bundle exec rails db:migrate"

[env]
  PORT = "8080"
  SERVER_COMMAND = "bundle exec puma"

[processes]
  app = "bundle exec puma -C config/puma.rb"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
