# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
    steps:
      - checkout

      - run:
          name: Install bundler
          command: gem install bundler -v '2.0.1'

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Database setup
          command: bundle exec rake db:setup

      # Run rspec in parallel
      - run:
          name: Run minitest
          command: bundle exec rake test
