version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
    version_requirement_updates: "auto"
    default_reviewers:
      - larouxn
    default_labels:
      - "Gem upgrades"